INSERT INTO `country_list` VALUES (null, 'AF', 'Afghanistan');
INSERT INTO `country_list` VALUES (null, 'AL', 'Albania');
INSERT INTO `country_list` VALUES (null, 'DZ', 'Algeria');
INSERT INTO `country_list` VALUES (null, 'DS', 'American Samoa');
INSERT INTO `country_list` VALUES (null, 'AD', 'Andorra');
INSERT INTO `country_list` VALUES (null, 'AO', 'Angola');
INSERT INTO `country_list` VALUES (null, 'AI', 'Anguilla');
INSERT INTO `country_list` VALUES (null, 'AQ', 'Antarctica');
INSERT INTO `country_list` VALUES (null, 'AG', 'Antigua and Barbuda');
INSERT INTO `country_list` VALUES (null, 'AR', 'Argentina');
INSERT INTO `country_list` VALUES (null, 'AM', 'Armenia');
INSERT INTO `country_list` VALUES (null, 'AW', 'Aruba');
INSERT INTO `country_list` VALUES (null, 'AU', 'Australia');
INSERT INTO `country_list` VALUES (null, 'AT', 'Austria');
INSERT INTO `country_list` VALUES (null, 'AZ', 'Azerbaijan');
INSERT INTO `country_list` VALUES (null, 'BS', 'Bahamas');
INSERT INTO `country_list` VALUES (null, 'BH', 'Bahrain');
INSERT INTO `country_list` VALUES (null, 'BD', 'Bangladesh');
INSERT INTO `country_list` VALUES (null, 'BB', 'Barbados');
INSERT INTO `country_list` VALUES (null, 'BY', 'Belarus');
INSERT INTO `country_list` VALUES (null, 'BE', 'Belgium');
INSERT INTO `country_list` VALUES (null, 'BZ', 'Belize');
INSERT INTO `country_list` VALUES (null, 'BJ', 'Benin');
INSERT INTO `country_list` VALUES (null, 'BM', 'Bermuda');
INSERT INTO `country_list` VALUES (null, 'BT', 'Bhutan');
INSERT INTO `country_list` VALUES (null, 'BO', 'Bolivia');
INSERT INTO `country_list` VALUES (null, 'BA', 'Bosnia and Herzegovina');
INSERT INTO `country_list` VALUES (null, 'BW', 'Botswana');
INSERT INTO `country_list` VALUES (null, 'BV', 'Bouvet Island');
INSERT INTO `country_list` VALUES (null, 'BR', 'Brazil');
INSERT INTO `country_list` VALUES (null, 'IO', 'British Indian Ocean Territory');
INSERT INTO `country_list` VALUES (null, 'BN', 'Brunei Darussalam');
INSERT INTO `country_list` VALUES (null, 'BG', 'Bulgaria');
INSERT INTO `country_list` VALUES (null, 'BF', 'Burkina Faso');
INSERT INTO `country_list` VALUES (null, 'BI', 'Burundi');
INSERT INTO `country_list` VALUES (null, 'KH', 'Cambodia');
INSERT INTO `country_list` VALUES (null, 'CM', 'Cameroon');
INSERT INTO `country_list` VALUES (null, 'CA', 'Canada');
INSERT INTO `country_list` VALUES (null, 'CV', 'Cape Verde');
INSERT INTO `country_list` VALUES (null, 'KY', 'Cayman Islands');
INSERT INTO `country_list` VALUES (null, 'CF', 'Central African Republic');
INSERT INTO `country_list` VALUES (null, 'TD', 'Chad');
INSERT INTO `country_list` VALUES (null, 'CL', 'Chile');
INSERT INTO `country_list` VALUES (null, 'CN', 'China');
INSERT INTO `country_list` VALUES (null, 'CX', 'Christmas Island');
INSERT INTO `country_list` VALUES (null, 'CC', 'Cocos (Keeling) Islands');
INSERT INTO `country_list` VALUES (null, 'CO', 'Colombia');
INSERT INTO `country_list` VALUES (null, 'KM', 'Comoros');
INSERT INTO `country_list` VALUES (null, 'CG', 'Congo');
INSERT INTO `country_list` VALUES (null, 'CK', 'Cook Islands');
INSERT INTO `country_list` VALUES (null, 'CR', 'Costa Rica');
INSERT INTO `country_list` VALUES (null, 'HR', 'Croatia (Hrvatska)');
INSERT INTO `country_list` VALUES (null, 'CU', 'Cuba');
INSERT INTO `country_list` VALUES (null, 'CY', 'Cyprus');
INSERT INTO `country_list` VALUES (null, 'CZ', 'Czech Republic');
INSERT INTO `country_list` VALUES (null, 'DK', 'Denmark');
INSERT INTO `country_list` VALUES (null, 'DJ', 'Djibouti');
INSERT INTO `country_list` VALUES (null, 'DM', 'Dominica');
INSERT INTO `country_list` VALUES (null, 'DO', 'Dominican Republic');
INSERT INTO `country_list` VALUES (null, 'TP', 'East Timor');
INSERT INTO `country_list` VALUES (null, 'EC', 'Ecuador');
INSERT INTO `country_list` VALUES (null, 'EG', 'Egypt');
INSERT INTO `country_list` VALUES (null, 'SV', 'El Salvador');
INSERT INTO `country_list` VALUES (null, 'GQ', 'Equatorial Guinea');
INSERT INTO `country_list` VALUES (null, 'ER', 'Eritrea');
INSERT INTO `country_list` VALUES (null, 'EE', 'Estonia');
INSERT INTO `country_list` VALUES (null, 'ET', 'Ethiopia');
INSERT INTO `country_list` VALUES (null, 'FK', 'Falkland Islands (Malvinas)');
INSERT INTO `country_list` VALUES (null, 'FO', 'Faroe Islands');
INSERT INTO `country_list` VALUES (null, 'FJ', 'Fiji');
INSERT INTO `country_list` VALUES (null, 'FI', 'Finland');
INSERT INTO `country_list` VALUES (null, 'FR', 'France');
INSERT INTO `country_list` VALUES (null, 'FX', 'France, Metropolitan');
INSERT INTO `country_list` VALUES (null, 'GF', 'French Guiana');
INSERT INTO `country_list` VALUES (null, 'PF', 'French Polynesia');
INSERT INTO `country_list` VALUES (null, 'TF', 'French Southern Territories');
INSERT INTO `country_list` VALUES (null, 'GA', 'Gabon');
INSERT INTO `country_list` VALUES (null, 'GM', 'Gambia');
INSERT INTO `country_list` VALUES (null, 'GE', 'Georgia');
INSERT INTO `country_list` VALUES (null, 'DE', 'Germany');
INSERT INTO `country_list` VALUES (null, 'GH', 'Ghana');
INSERT INTO `country_list` VALUES (null, 'GI', 'Gibraltar');
INSERT INTO `country_list` VALUES (null, 'GK', 'Guernsey');
INSERT INTO `country_list` VALUES (null, 'GR', 'Greece');
INSERT INTO `country_list` VALUES (null, 'GL', 'Greenland');
INSERT INTO `country_list` VALUES (null, 'GD', 'Grenada');
INSERT INTO `country_list` VALUES (null, 'GP', 'Guadeloupe');
INSERT INTO `country_list` VALUES (null, 'GU', 'Guam');
INSERT INTO `country_list` VALUES (null, 'GT', 'Guatemala');
INSERT INTO `country_list` VALUES (null, 'GN', 'Guinea');
INSERT INTO `country_list` VALUES (null, 'GW', 'Guinea-Bissau');
INSERT INTO `country_list` VALUES (null, 'GY', 'Guyana');
INSERT INTO `country_list` VALUES (null, 'HT', 'Haiti');
INSERT INTO `country_list` VALUES (null, 'HM', 'Heard and Mc Donald Islands');
INSERT INTO `country_list` VALUES (null, 'HN', 'Honduras');
INSERT INTO `country_list` VALUES (null, 'HK', 'Hong Kong');
INSERT INTO `country_list` VALUES (null, 'HU', 'Hungary');
INSERT INTO `country_list` VALUES (null, 'IS', 'Iceland');
INSERT INTO `country_list` VALUES (null, 'IN', 'India');
INSERT INTO `country_list` VALUES (null, 'IM', 'Isle of Man');
INSERT INTO `country_list` VALUES (null, 'ID', 'Indonesia');
INSERT INTO `country_list` VALUES (null, 'IR', 'Iran (Islamic Republic of)');
INSERT INTO `country_list` VALUES (null, 'IQ', 'Iraq');
INSERT INTO `country_list` VALUES (null, 'IE', 'Ireland');
INSERT INTO `country_list` VALUES (null, 'IL', 'Israel');
INSERT INTO `country_list` VALUES (null, 'IT', 'Italy');
INSERT INTO `country_list` VALUES (null, 'CI', 'Ivory Coast');
INSERT INTO `country_list` VALUES (null, 'JE', 'Jersey');
INSERT INTO `country_list` VALUES (null, 'JM', 'Jamaica');
INSERT INTO `country_list` VALUES (null, 'JP', 'Japan');
INSERT INTO `country_list` VALUES (null, 'JO', 'Jordan');
INSERT INTO `country_list` VALUES (null, 'KZ', 'Kazakhstan');
INSERT INTO `country_list` VALUES (null, 'KE', 'Kenya');
INSERT INTO `country_list` VALUES (null, 'KI', 'Kiribati');
INSERT INTO `country_list` VALUES (null, 'KP', 'Korea, Democratic People''s Republic of');
INSERT INTO `country_list` VALUES (null, 'KR', 'Korea, Republic of');
INSERT INTO `country_list` VALUES (null, 'XK', 'Kosovo');
INSERT INTO `country_list` VALUES (null, 'KW', 'Kuwait');
INSERT INTO `country_list` VALUES (null, 'KG', 'Kyrgyzstan');
INSERT INTO `country_list` VALUES (null, 'LA', 'Lao People''s Democratic Republic');
INSERT INTO `country_list` VALUES (null, 'LV', 'Latvia');
INSERT INTO `country_list` VALUES (null, 'LB', 'Lebanon');
INSERT INTO `country_list` VALUES (null, 'LS', 'Lesotho');
INSERT INTO `country_list` VALUES (null, 'LR', 'Liberia');
INSERT INTO `country_list` VALUES (null, 'LY', 'Libyan Arab Jamahiriya');
INSERT INTO `country_list` VALUES (null, 'LI', 'Liechtenstein');
INSERT INTO `country_list` VALUES (null, 'LT', 'Lithuania');
INSERT INTO `country_list` VALUES (null, 'LU', 'Luxembourg');
INSERT INTO `country_list` VALUES (null, 'MO', 'Macau');
INSERT INTO `country_list` VALUES (null, 'MK', 'Macedonia');
INSERT INTO `country_list` VALUES (null, 'MG', 'Madagascar');
INSERT INTO `country_list` VALUES (null, 'MW', 'Malawi');
INSERT INTO `country_list` VALUES (null, 'MY', 'Malaysia');
INSERT INTO `country_list` VALUES (null, 'MV', 'Maldives');
INSERT INTO `country_list` VALUES (null, 'ML', 'Mali');
INSERT INTO `country_list` VALUES (null, 'MT', 'Malta');
INSERT INTO `country_list` VALUES (null, 'MH', 'Marshall Islands');
INSERT INTO `country_list` VALUES (null, 'MQ', 'Martinique');
INSERT INTO `country_list` VALUES (null, 'MR', 'Mauritania');
INSERT INTO `country_list` VALUES (null, 'MU', 'Mauritius');
INSERT INTO `country_list` VALUES (null, 'TY', 'Mayotte');
INSERT INTO `country_list` VALUES (null, 'MX', 'Mexico');
INSERT INTO `country_list` VALUES (null, 'FM', 'Micronesia, Federated States of');
INSERT INTO `country_list` VALUES (null, 'MD', 'Moldova, Republic of');
INSERT INTO `country_list` VALUES (null, 'MC', 'Monaco');
INSERT INTO `country_list` VALUES (null, 'MN', 'Mongolia');
INSERT INTO `country_list` VALUES (null, 'ME', 'Montenegro');
INSERT INTO `country_list` VALUES (null, 'MS', 'Montserrat');
INSERT INTO `country_list` VALUES (null, 'MA', 'Morocco');
INSERT INTO `country_list` VALUES (null, 'MZ', 'Mozambique');
INSERT INTO `country_list` VALUES (null, 'MM', 'Myanmar');
INSERT INTO `country_list` VALUES (null, 'NA', 'Namibia');
INSERT INTO `country_list` VALUES (null, 'NR', 'Nauru');
INSERT INTO `country_list` VALUES (null, 'NP', 'Nepal');
INSERT INTO `country_list` VALUES (null, 'NL', 'Netherlands');
INSERT INTO `country_list` VALUES (null, 'AN', 'Netherlands Antilles');
INSERT INTO `country_list` VALUES (null, 'NC', 'New Caledonia');
INSERT INTO `country_list` VALUES (null, 'NZ', 'New Zealand');
INSERT INTO `country_list` VALUES (null, 'NI', 'Nicaragua');
INSERT INTO `country_list` VALUES (null, 'NE', 'Niger');
INSERT INTO `country_list` VALUES (null, 'NG', 'Nigeria');
INSERT INTO `country_list` VALUES (null, 'NU', 'Niue');
INSERT INTO `country_list` VALUES (null, 'NF', 'Norfolk Island');
INSERT INTO `country_list` VALUES (null, 'MP', 'Northern Mariana Islands');
INSERT INTO `country_list` VALUES (null, 'NO', 'Norway');
INSERT INTO `country_list` VALUES (null, 'OM', 'Oman');
INSERT INTO `country_list` VALUES (null, 'PK', 'Pakistan');
INSERT INTO `country_list` VALUES (null, 'PW', 'Palau');
INSERT INTO `country_list` VALUES (null, 'PS', 'Palestine');
INSERT INTO `country_list` VALUES (null, 'PA', 'Panama');
INSERT INTO `country_list` VALUES (null, 'PG', 'Papua New Guinea');
INSERT INTO `country_list` VALUES (null, 'PY', 'Paraguay');
INSERT INTO `country_list` VALUES (null, 'PE', 'Peru');
INSERT INTO `country_list` VALUES (null, 'PH', 'Philippines');
INSERT INTO `country_list` VALUES (null, 'PN', 'Pitcairn');
INSERT INTO `country_list` VALUES (null, 'PL', 'Poland');
INSERT INTO `country_list` VALUES (null, 'PT', 'Portugal');
INSERT INTO `country_list` VALUES (null, 'PR', 'Puerto Rico');
INSERT INTO `country_list` VALUES (null, 'QA', 'Qatar');
INSERT INTO `country_list` VALUES (null, 'RE', 'Reunion');
INSERT INTO `country_list` VALUES (null, 'RO', 'Romania');
INSERT INTO `country_list` VALUES (null, 'RU', 'Russian Federation');
INSERT INTO `country_list` VALUES (null, 'RW', 'Rwanda');
INSERT INTO `country_list` VALUES (null, 'KN', 'Saint Kitts and Nevis');
INSERT INTO `country_list` VALUES (null, 'LC', 'Saint Lucia');
INSERT INTO `country_list` VALUES (null, 'VC', 'Saint Vincent and the Grenadines');
INSERT INTO `country_list` VALUES (null, 'WS', 'Samoa');
INSERT INTO `country_list` VALUES (null, 'SM', 'San Marino');
INSERT INTO `country_list` VALUES (null, 'ST', 'Sao Tome and Principe');
INSERT INTO `country_list` VALUES (null, 'SA', 'Saudi Arabia');
INSERT INTO `country_list` VALUES (null, 'SN', 'Senegal');
INSERT INTO `country_list` VALUES (null, 'RS', 'Serbia');
INSERT INTO `country_list` VALUES (null, 'SC', 'Seychelles');
INSERT INTO `country_list` VALUES (null, 'SL', 'Sierra Leone');
INSERT INTO `country_list` VALUES (null, 'SG', 'Singapore');
INSERT INTO `country_list` VALUES (null, 'SK', 'Slovakia');
INSERT INTO `country_list` VALUES (null, 'SI', 'Slovenia');
INSERT INTO `country_list` VALUES (null, 'SB', 'Solomon Islands');
INSERT INTO `country_list` VALUES (null, 'SO', 'Somalia');
INSERT INTO `country_list` VALUES (null, 'ZA', 'South Africa');
INSERT INTO `country_list` VALUES (null, 'GS', 'South Georgia South Sandwich Islands');
INSERT INTO `country_list` VALUES (null, 'SS', 'South Sudan');
INSERT INTO `country_list` VALUES (null, 'ES', 'Spain');
INSERT INTO `country_list` VALUES (null, 'LK', 'Sri Lanka');
INSERT INTO `country_list` VALUES (null, 'SH', 'St. Helena');
INSERT INTO `country_list` VALUES (null, 'PM', 'St. Pierre and Miquelon');
INSERT INTO `country_list` VALUES (null, 'SD', 'Sudan');
INSERT INTO `country_list` VALUES (null, 'SR', 'Suriname');
INSERT INTO `country_list` VALUES (null, 'SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO `country_list` VALUES (null, 'SZ', 'Swaziland');
INSERT INTO `country_list` VALUES (null, 'SE', 'Sweden');
INSERT INTO `country_list` VALUES (null, 'CH', 'Switzerland');
INSERT INTO `country_list` VALUES (null, 'SY', 'Syrian Arab Republic');
INSERT INTO `country_list` VALUES (null, 'TW', 'Taiwan');
INSERT INTO `country_list` VALUES (null, 'TJ', 'Tajikistan');
INSERT INTO `country_list` VALUES (null, 'TZ', 'Tanzania, United Republic of');
INSERT INTO `country_list` VALUES (null, 'TH', 'Thailand');
INSERT INTO `country_list` VALUES (null, 'TG', 'Togo');
INSERT INTO `country_list` VALUES (null, 'TK', 'Tokelau');
INSERT INTO `country_list` VALUES (null, 'TO', 'Tonga');
INSERT INTO `country_list` VALUES (null, 'TT', 'Trinidad and Tobago');
INSERT INTO `country_list` VALUES (null, 'TN', 'Tunisia');
INSERT INTO `country_list` VALUES (null, 'TR', 'Turkey');
INSERT INTO `country_list` VALUES (null, 'TM', 'Turkmenistan');
INSERT INTO `country_list` VALUES (null, 'TC', 'Turks and Caicos Islands');
INSERT INTO `country_list` VALUES (null, 'TV', 'Tuvalu');
INSERT INTO `country_list` VALUES (null, 'UG', 'Uganda');
INSERT INTO `country_list` VALUES (null, 'UA', 'Ukraine');
INSERT INTO `country_list` VALUES (null, 'AE', 'United Arab Emirates');
INSERT INTO `country_list` VALUES (null, 'GB', 'United Kingdom');
INSERT INTO `country_list` VALUES (null, 'US', 'United States');
INSERT INTO `country_list` VALUES (null, 'UM', 'United States minor outlying islands');
INSERT INTO `country_list` VALUES (null, 'UY', 'Uruguay');
INSERT INTO `country_list` VALUES (null, 'UZ', 'Uzbekistan');
INSERT INTO `country_list` VALUES (null, 'VU', 'Vanuatu');
INSERT INTO `country_list` VALUES (null, 'VA', 'Vatican City State');
INSERT INTO `country_list` VALUES (null, 'VE', 'Venezuela');
INSERT INTO `country_list` VALUES (null, 'VN', 'Vietnam');
INSERT INTO `country_list` VALUES (null, 'VG', 'Virgin Islands (British)');
INSERT INTO `country_list` VALUES (null, 'VI', 'Virgin Islands (U.S.)');
INSERT INTO `country_list` VALUES (null, 'WF', 'Wallis and Futuna Islands');
INSERT INTO `country_list` VALUES (null, 'EH', 'Western Sahara');
INSERT INTO `country_list` VALUES (null, 'YE', 'Yemen');
INSERT INTO `country_list` VALUES (null, 'ZR', 'Zaire');
INSERT INTO `country_list` VALUES (null, 'ZM', 'Zambia');
INSERT INTO `country_list` VALUES (null, 'ZW', 'Zimbabwe');