name: Deploy to master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Clean up untracked files
        run: |
          git reset --hard HEAD
          git clean -fd
      - name: Commit built assets
        run: |
          git config --local user.email "aasthastha143@gmail.com"
          git config --local user.name "Aastha Shrestha"
          git checkout -B master-deploy
          git add -f public/
          if ! git diff --cached --quiet; then
            git commit -m "Build front-end assets"
            git push -f origin master-deploy
          else
            echo "No changes to commit. Skipping push."
          fi
          git push -f origin master-deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to master
        uses: appleboy/ssh-action@master
        with:
          username: ${{ vars.MASTER_SSH_USERNAME }}
          host: ${{ vars.MASTER_SSH_HOST }}
          key: ${{ secrets.MASTER_SSH_KEY }}
          port: ${{ vars.MASTER_SSH_PORT }}
          script: |
            cd ${{ vars.MASTER_SSH_PATH }}
            chmod +x ./master-deploy.sh
            ./master-deploy.sh
             
  delete:
    name: Delete master-deploy branch
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Delete master-deploy branch
        run: |
          git config --local user.email "aasthastha143@gmail.com"
          git config --local user.name "Aastha Shrestha"
          git push origin --delete master-deploy

  lower_branch:
    name: Create lower branch
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Fetch all branches
        run: |
          git config --local user.email "aasthastha143@gmail.com"
          git config --local user.name "Aastha Shrestha"
          git fetch --all
      - name: Create lower branch
        run: |
          git checkout -B ${{ vars.MASTER_LOWER_BRANCH }}
          git push -f origin ${{ vars.MASTER_LOWER_BRANCH }}
