<?php

use Illuminate\Database\Seeder;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts = array(
            array('type' => 'district', 'name' => 'Bhojpur'),
            array('type' => 'district', 'name' => 'Dhankuta'),
            array('type' => 'district', 'name' => 'Ilam'),
            array('type' => 'district', 'name' => 'Jhapa'),
            array('type' => 'district', 'name' => 'Khotang'),
            array('type' => 'district', 'name' => 'Morang'),
            array('type' => 'district', 'name' => 'Okhaldhunga'),
            array('type' => 'district', 'name' => 'Panchthar'),
            array('type' => 'district', 'name' => 'Sankhuwasabha'),
            array('type' => 'district', 'name' => 'Solukhumbu'),
            array('type' => 'district', 'name' => 'Sunsari'),
            array('type' => 'district', 'name' => 'Taplejung'),
            array('type' => 'district', 'name' => 'Terhathum'),
            array('type' => 'district', 'name' => 'Udayapur'),
            array('type' => 'district', 'name' => 'Saptari'),
            array('type' => 'district', 'name' => 'Siraha'),
            array('type' => 'district', 'name' => 'Dhanusa'),
            array('type' => 'district', 'name' => 'Mahottari'),
            array('type' => 'district', 'name' => 'Sarlahi'),
            array('type' => 'district', 'name' => 'Bara'),
            array('type' => 'district', 'name' => 'Parsa'),
            array('type' => 'district', 'name' => 'Rautahat'),
            array('type' => 'district', 'name' => 'Sindhuli'),
            array('type' => 'district', 'name' => 'Ramechhap'),
            array('type' => 'district', 'name' => 'Dolakha'),
            array('type' => 'district', 'name' => 'Bhaktapur'),
            array('type' => 'district', 'name' => 'Dhading'),
            array('type' => 'district', 'name' => 'Kathmandu'),
            array('type' => 'district', 'name' => 'Kavrepalanchok'),
            array('type' => 'district', 'name' => 'Lalitpur'),
            array('type' => 'district', 'name' => 'Nuwakot'),
            array('type' => 'district', 'name' => 'Rasuwa'),
            array('type' => 'district', 'name' => 'Sindhupalchok'),
            array('type' => 'district', 'name' => 'Chitwan'),
            array('type' => 'district', 'name' => 'Makwanpur'),
            array('type' => 'district', 'name' => 'Baglung'),
            array('type' => 'district', 'name' => 'Gorkha'),
            array('type' => 'district', 'name' => 'Kaski'),
            array('type' => 'district', 'name' => 'Lamjung'),
            array('type' => 'district', 'name' => 'Manang'),
            array('type' => 'district', 'name' => 'Mustang'),
            array('type' => 'district', 'name' => 'Myagdi'),
            array('type' => 'district', 'name' => 'Nawalpur'),
            array('type' => 'district', 'name' => 'Parbat'),
            array('type' => 'district', 'name' => 'Syangja'),
            array('type' => 'district', 'name' => 'Tanahun'),
            array('type' => 'district', 'name' => 'Kapilvastu'),
            array('type' => 'district', 'name' => 'Parasi'),
            array('type' => 'district', 'name' => 'Rupandehi'),
            array('type' => 'district', 'name' => 'Arghakhanchi'),
            array('type' => 'district', 'name' => 'Gulmi'),
            array('type' => 'district', 'name' => 'Palpa'),
            array('type' => 'district', 'name' => 'Dang'),
            array('type' => 'district', 'name' => 'Pyuthan'),
            array('type' => 'district', 'name' => 'Rolpa'),
            array('type' => 'district', 'name' => 'Eastern Rukum'),
            array('type' => 'district', 'name' => 'Banke'),
            array('type' => 'district', 'name' => 'Bardiya'),
            array('type' => 'district', 'name' => 'Western Rukum'),
            array('type' => 'district', 'name' => 'Salyan'),
            array('type' => 'district', 'name' => 'Dolpa'),
            array('type' => 'district', 'name' => 'Humla'),
            array('type' => 'district', 'name' => 'Jumla'),
            array('type' => 'district', 'name' => 'Kalikot'),
            array('type' => 'district', 'name' => 'Mugu'),
            array('type' => 'district', 'name' => 'Surkhet'),
            array('type' => 'district', 'name' => 'Dailekh'),
            array('type' => 'district', 'name' => 'Jajarkot'),
            array('type' => 'district', 'name' => 'Kailali'),
            array('type' => 'district', 'name' => 'Achham'),
            array('type' => 'district', 'name' => 'Doti'),
            array('type' => 'district', 'name' => 'Bajhang'),
            array('type' => 'district', 'name' => 'Bajura'),
            array('type' => 'district', 'name' => 'Kanchanpur'),
            array('type' => 'district', 'name' => 'Dadeldhura'),
            array('type' => 'district', 'name' => 'Baitadi'),
            array('type' => 'district', 'name' => 'Darchula'),
            array('type' => 'np_state', 'name' => 'Central Development'),
            array('type' => 'np_state', 'name' => 'Western Development'),
            array('type' => 'np_state', 'name' => 'Mid-Western Development'),
            array('type' => 'np_state', 'name' => 'Far-Western Development'),
            array('type' => 'np_state', 'name' => 'Eastern Development Region'),
        );
        \Illuminate\Support\Facades\DB::table('australian_states')->insert($districts);
    }
}
